#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

MAX_ENV_STEPS=${MAX_ENV_STEPS:-1000}
ENV_CONFIG_BASE=${ENV_CONFIG_BASE:-parallelr2drl_11vs11scenario_catalog_front-goal-1v1_opp-lv3_goal-only}

ENV_CONFIG="$ENV_CONFIG_BASE" MAX_ENV_STEPS="$MAX_ENV_STEPS" PORT_START=${QMIX_PORT_START:-6000} PORT_END=${QMIX_PORT_END:-8000} "$SCRIPT_DIR/run_qmix_demo.sh"
ENV_CONFIG="$ENV_CONFIG_BASE" MAX_ENV_STEPS="$MAX_ENV_STEPS" PORT_START=${MAPPO_PORT_START:-6100} PORT_END=${MAPPO_PORT_END:-8100} "$SCRIPT_DIR/run_mappo_demo.sh"
ENV_CONFIG="${ENV_CONFIG_BASE}.yaml" MAX_ENV_STEPS="$MAX_ENV_STEPS" PORT_START=${PARADQN_PORT_START:-6200} PORT_END=${PARADQN_PORT_END:-8200} "$SCRIPT_DIR/run_paradqn_demo.sh"
